package com.beemobi.rongthanonline.top;

public enum TopType {
    POWER_MASTER, POWER_DISCIPLE, MARTIAL_ARTS_FESTIVAL, TOP_SURVIVAL, TOP_EVENT,
    TOP_HERO, TOP_ACTIVE, TOP_CLAN, TOP_HERO_LAST_WEEK, TOP_ACTIVE_LAST_WEEK, TOP_TREASURE,
    TOP_EVENT_OTHER, TOP_EVENT_WEEK, TOP_EVENT_LAST_WEEK, TOP_EVENT_WEEK_OTHER, TOP_EVENT_LAST_WEEK_OTHER, TOP_PRO,
    TOP_EVENT_WEEKLY, TOP_EVENT_OTHER_WEEKLY, TOP_EVENT_OTHER_PREVIOUS_WEEKLY, TOP_EVENT_PREVIOUS_WEEKLY,
    TOP_BOSS_WEEKLY, TOP_BOSS_PREVIOUS_WEEKLY, TOP_ACTIVE_WEEKLY, TOP_ACTIVE_PREVIOUS_WEEKLY
}
