# ===============================
# DATABASE
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/rto
spring.datasource.username=root
spring.datasource.password=
server.port=0707
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
# ===============================
# SERVER VERSION
# ===============================
server.image.version=13
server.item.template.version=72
server.item.option.version=56
server.npc.template.version=25
server.effect.template.version=20
server.medal.version=31
server.aura.version=10
server.level.version=18
server.frame.version=41
server.mount.version=22
server.monster.version=22
server.bag.version=21
server.skill.paint.version=17

# Static resources cache (cpanel)
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.chain.cache=false