package com.beemobi.rongthanonline.shop;

public enum ShopType {
    SHOP_BUNMA_EQUIP, SHOP_BUNMA_OTHER, SHOP_AMULET_TIME, SHOP_AMULET_OTHER,
    SHOP_CLAN, SHOP_BARRACK, SHOP_REPURCHASE, SHOP_ACTIVE, SHOP_CONSIGNMENT,
    SHOP_YARDRAT, SHOP_EVENT, SHOP_BLACK_FRIDAY, SHOP_RIDER, SHOP_SPACESHIP,
    SHOP_FLAG_WAR
}
