package com.beemobi.rongthanonline.upgrade;

public enum UpgradeType {
    UPGRADE_ITEM, UPGRADE_STONE, CRYSTALLIZE, POLISH, ENCHANT_ITEM, COMBINE,
    EQUIP_CRAFTING_3X, EQUIP_CRAFTING_4X, COSTUME_MERGING, REFRESH_ITEM_3X,
    REFRESH_ITEM_4X, REFRESH_MAX_ITEM, EQUIP_CRAFTING_6X, UP_STAR_PET,
    EQUIP_CRAFTING_RIDER, CHANGE_OPTION_RIDER, UPGRADE_ITEM_RIDER, PACK_AVATAR,
    CRAFTING_PORATA, OPEN_OPTION_PORATA, REMOVE_OPTION, CHE_TAO_THIEN_SU,
    PACK_THU_CUOI, UPGRADE_PORATA, REMOVE_STAR, GHEP_HUY_HIEU, TACH_HUY_HIEU,
    GHEP_CAI_TRANG, TACH_CAI_TRANG, GHEP_DEO_LUNG, TACH_DEO_LUNG, GHEP_THU_CUOI, TACH_THU_CUOI,
    GHEP_AURA, TACH_AURA, GHEP_HUY_HIEU_DAI_GIA, DOI_DA_9, DOI_CAPSULE_HUYEN_BI, NANG_TRANG_BI_PET,
    DOI_TRANG_BI_PET, DOI_HOA_HONG
}
